version: "3.8"
services:
  jobs-connection-rabbitmq-broker:
    image: rabbitmq:3.12.0-management-alpine
    container_name: 'jobs-connection-rabbitmq-broker'
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_jobs_connection

networks:
  rabbitmq_jobs_connection:
    driver: bridge